version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/komga-webui"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/komga"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "weekly"
